#!/home/jfichte/anaconda3/envs/rb/bin/python
# -*- coding: utf-8 -*-
import re
import sys

from reprobench.console.main import cli

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
